### ISSUE TITLE
Sadad: Technical Error

### ISSUE THREAD

**Issue by ahmad-shawky** [moyasar/moyasar-ruby#10]
I try to create a payment using sadad. i sent parameters according to docs.
I get `Technical error`

Bellow is response of returned object

`<Moyasar::Payment:0x007f8c38e345b0 @source=#<Moyasar::Sadad:0x007f8c38e34290 @username="xxxxxxxx", @error_code="E999999", @message="Technical Error Occured", @transaction_id=nil, @transaction_url=nil>, @id="951b458a-4cda-4d90-9f25-1470ec3ce485", @status="failed", @amount=84235, @fee=0, @currency="SAR", @refunded=0, @refunded_at=nil, @description="xxxxxxx", @amount_format="842.35 SAR", @fee_format="0.00 SAR", @refunded_format="0.00 SAR", @invoice_id=nil, @ip="51.36.57.51", @callback_url="http://localhost:3000/xxxxxx", @created_at="2018-02-26T19:42:52.146Z", @updated_at="2018-02-26T19:42:53.439Z">`

**Comment by tareifz** [comment]
This error happens with Sadad sometimes, you need to try creating the payment again.

**Comment by ahmad-shawky** [comment]
@tareifz Thanks for your response. I tried many times but issue still exist

**Comment by tareifz** [comment]
@abarrak FYI

**Comment by abarrak** [comment]
This is a well known issue within the bank test environment currently as it going through new version.

The temporary solution is to test via your live account.
Please contact [Moyasar support](mailto:support@moyasar.com) for any related Sadad account or activation issue.
