### ISSUE TITLE
Wrong card number throw NoMethodError

### ISSUE THREAD

**Issue by AhmedShawkyPW** [moyasar/moyasar-ruby#6]
When i use wrong credit card number i didn't get error message and i get exception

```
 NoMethodError: undefined method `keys' for "'unknown' is not a valid company":String

```

**Comment by abarrak** [comment]
Hi, and thanks for reporting the issue @AhmedShawkyPW ..

I can't reproduce the bug with the gem's [latest version (0.6.0)](https://rubygems.org/gems/moyasar/versions/0.6.0)

It seems to be the same as a reoccurring bug [found and fixed](https://github.com/moyasar/moyasar-ruby/pull/4/commits/a6311547d807e064f14270f8654d4dc81271bcd5) in the previous v0.4.0 (I was able to reproduce it with the later version).

Please make sure to update your version, and inform us if the issue persists.

**Comment by AhmedShawkyPW** [comment]
@abarrak Now i get Moyasar::InvalidRequestError wrong number of parameters with card number: "488565655555555"

**Comment by abarrak** [comment]
Yes, this is the [API registered error](https://moyasar.com/docs/api/?ruby#http-status-code) and probably would have a `rescue` as your preference.

**Comment by AhmedShawkyPW** [comment]
@abarrak But this not a descriptive error. I hope you build descriptive error for such cases. Thanks for your help

**Comment by abarrak** [comment]
Alright @AhmedShawkyPW. My please. 
We try to give indication about any failing operation with as much information as possible in the returned error object.

Your valuable suggestion is duly noted and will be reflected within coming API updates ..

**Comment by AhmedShawkyPW** [comment]
@abarrak Thanks for your quick support.
