### ISSUE TITLE
Validation Failed: company can be visa or mastercard only

### ISSUE THREAD

**Issue by ahmad-shawky** [moyasar/moyasar-ruby#9]
I trying to create payment using credit card. i sent parameters according to docs. 
https://moyasar.com/docs/api/#arguments
I get error `Moyasar::InvalidRequestError: Validation Failed: company can be visa or mastercard only`
even company parameter is not required in docs.

I added also company parameter and i still get the same error.

**Comment by tareifz** [comment]
Double check the credit card number you are using.

**Comment by ahmad-shawky** [comment]
You are right. The number is wrong. its good thing to if you could make message something like. 
`Your card number type is not supported. only visa and mastercard number supported`

Thank you

**Comment by tareifz** [comment]
Thank you @ahmad-shawky , You can rest assured that we always try to improve our messages and services, your valuable suggestion is much appreciated.

**Comment by ahmad-shawky** [comment]
@tareifz Thanks
